[username]
format = " [â•­â”€$user]($style) on "
style_user = "bold bright-green"
style_root = "bold green"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "bold purple"
trim_at = "-"
ssh_only = false
disabled = false

[cmd_duration]
min_time = 10
format = "took [$duration]($style)"

[character]
success_symbol = " [â†’](bold red)"
error_symbol = " [Ã—](bold red)"

[battery]
full_symbol = " â•°â”€ğŸ”‹ "
charging_symbol = " â•°â”€ğŸ”Œ "
discharging_symbol = " â•°â”€âš¡ "

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 80
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = -1
style = "bold dimmed white"
disabled = false

[directory]
style = "purple"
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "repo: "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸ£ "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸  Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸  Ã—${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[line_break]
disabled = false

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bold bright-white"
disabled = true

[aws]
format = "[$symbol$region]($style) "
style = "bold yellow"
symbol = "ó°¸ "

[azure]
format = "[$symbol$subscription]($style) "
style = "bold yellow"
symbol = "ó° … "

[conda]
format = "[$symbol$environment]($style) "
style = "bold green"
symbol = "ï„Œ "

[dart]
format = "[$symbol$version]($style) "
style = "bold blue"
symbol = "î™Œ "

[docker_context]
format = "[$symbol$context]($style) "
style = "bold blue"
symbol = "ïŒˆ "

[elixir]
format = "[$symbol$version]($style) "
style = "bold blue"
symbol = "î‰µ "

[elm]
format = "[$symbol$version]($style) "
style = "bold green"
symbol = "î˜¬ "

[golang]
format = "[$symbol$version]($style) "
style = "bold blue"
symbol = "î˜§ "

[hg_branch]
format = "[$symbol$branch]($style) "
style = "bold blue"
symbol = "ï˜ "

[java]
format = "[$symbol$version]($style) "
style = "bold orange"
symbol = "î‰– "

[julia]
format = "[$symbol$version]($style) "
style = "bold purple"
symbol = "î˜¤ "

[nim]
format = "[$symbol$version]($style) "
style = "bold yellow"
symbol = "î™· "

[nix_shell]
format = "[$symbol$state]($style) "
style = "bold blue"
symbol = "ï‹œ "

[nodejs]
format = "[$symbol$version]($style) "
style = "bold green"
symbol = "î‰ "

[package]
format = "is [$symbol$version]($style) "
style = "bold dimmed purple"
symbol = "ï’‡ "

[perl]
format = "[$symbol$version]($style) "
style = "bold dimmed blue"
symbol = "î© "

[php]
format = "[$symbol$version]($style) "
style = "bold dimmed purple"
symbol = "î˜ˆ "

[python]
format = "[$symbol${pyenv_prefix}$version]($style) "
style = "bold yellow"
symbol = "î˜† "

[ruby]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "îˆ¾ "

[rust]
format = "[$symbol$version]($style) "
style = "bold dimmed black"
symbol = "îš‹ "

[swift]
format = "[$symbol$version]($style) "
style = "bold orange"
symbol = "î• "
